# Generated by Django 3.2.25 on 2025-06-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('reseña', models.TextField()),
                ('numero_paginas', models.IntegerField()),
                ('autor', models.CharField(max_length=100)),
                ('sinopsis', models.TextField()),
            ],
        ),
    ]
