# Generated by Django 3.2.25 on 2025-06-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='numero_paginas',
            new_name='paginas',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='nombre',
        ),
        migrations.AddField(
            model_name='libro',
            name='imagen',
            field=models.URLField(default=1, help_text='Pega la URL de la portada del libro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='titulo',
            field=models.CharField(default='valor por defecto', max_length=200),
            preserve_default=False,
        ),
    ]
